version: "3"
services:
  reactapp:
    build:
      context: ./client
    image: faresatef/pern-app:react-app
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - nodeapp
  
  nodeapp:
    build:
      context: ./server
    image: faresatef/pern-app:node-app
    container_name: node-app
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: